repos:
  - repo: https://github.com/python/black.git
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          [
            "--max-line-length",
            "120",
            "--extend-ignore",
            "E203,BLK100,W605,ANN002,ANN003,ANN101,ANN204",
            "--docstring-convention",
            "google",
          ]
        additional_dependencies:
          - flake8-black==0.2.4
          - flake8-docstrings==1.7.0
          - flake8-annotations==3.1.1
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--line-length",
            "120",
            "--extend-skip",
            "__init__.py",
            "--filter-files",
          ]